name: CI

on:
  pull_request:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
      - 'feature/*'

jobs:
  pre-commit:
    name: "Run Pre-Commit Checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
  build:
    name: "Build Artifacts"
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          context: bootloader
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=local,dest=./out
      - name: Copy Artifacts
        run: |
          mkdir artifacts
          cp -r ./host-software ./artifacts
          mkdir ./artifacts/bootloader
          cp ./out/xcore-boot.bin ./artifacts/bootloader
          cp ./out/xcore-boot.elf ./artifacts/bootloader
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bootloader
          path: artifacts/
  tagged-release:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    needs: build
    steps:
      - name: Download artifacts from build stage
        uses: actions/download-artifact@v4
        with:
          name: bootloader
          path: artifacts
      - name: Compress release directory into a versioned ZIP file
        run: zip -r "xcore-boot-${{ github.ref_name }}.zip" artifacts/*
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: "xcore-boot-${{ github.ref_name }}.zip"

  build-host-docker:
    name: "Build Host Software Docker Image"
    needs: pre-commit
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-24.04-arm, ubuntu-24.04 ]
        include:
          - os: ubuntu-24.04-arm
            docker_build_arch: arm64
          - os: ubuntu-24.04
            docker_build_arch: amd64
    defaults:
      run:
        working-directory: ./host-software
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        env:
          REPOSITORY: '${{ github.repository }}'
        run: |
          build_arch=${{ matrix.docker_build_arch }}
          echo "BUILD_ARCH=${build_arch//\//-}" >> ${GITHUB_ENV}

          echo "REPOSITORY_LC=${REPOSITORY,,}" >> ${GITHUB_ENV}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.REPOSITORY_LC }}
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: host-software
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.docker_build_arch }}
          outputs: type=image,name=ghcr.io/${{ env.REPOSITORY_LC }},push-by-digest=true,name-canonical=true,push=true
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build-and-push.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.BUILD_ARCH }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
  merge:
    runs-on: ubuntu-24.04
    needs:
      - build-host-docker
    steps:
      - name: Prepare
        env:
          REPOSITORY: '${{ github.repository }}'
        run: |
          echo "REPOSITORY_LC=${REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # generate Docker tags based on the following events/attributes
          tags: |
            type=edge,branch=main,prefix=releases-
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
          images: ghcr.io/${{ env.REPOSITORY_LC }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf 'ghcr.io/${{ env.REPOSITORY_LC }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ghcr.io/${{ env.REPOSITORY_LC }}:${{ steps.meta.outputs.version }}
